name: Build
on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: jsii/superchain
    steps:
      - uses: actions/checkout@v2
      - name: installing dependencies
        run: tools/install-workflow-deps.sh
      - name: Running CI Cycle
        run: yarn ci
